name: vetratech_mobile_app
description: A Flutter app for veterinary reports.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  provider: ^6.1.4
  animated_text_kit: ^4.2.3
  shimmer: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.2.1
  go_router: ^14.8.1
  syncfusion_flutter_pdfviewer: ^29.1.37
  share_plus: ^10.1.4
  syncfusion_flutter_datepicker: ^29.1.37 # Replaces date_range_picker

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: ArabicFont
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
