name: Build Android APK -4

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  FLUTTER_VERSION: "3.16.9"
  ANDROID_HOME: /usr/local/lib/android/sdk

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          add-to-path: true

      - name: Accept Android Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          flutter doctor --android-licenses -y

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release \
            --dart-define=APP_ENV=prod \
            --split-per-abi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk
