name: Build Android APK -1

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.16.9"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Verified latest

      - name: Setup Java
        uses: actions/setup-java@v3  # Verified latest
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2  # Verified commit
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Accept Android Licenses
        run: |
          yes | sdkmanager --licenses || true
          flutter doctor --android-licenses --verbose

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release \
            --dart-define=APP_ENV=prod \
            --split-per-abi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk
