name: Build Flutter Android App -99

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java JDK (required for Android builds)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Use Java 17 (compatible with Flutter)
          distribution: 'temurin'

      # Step 3: Install Flutter SDK
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # Specify the Flutter version you are using

      # Step 4: Install Android dependencies
      - name: Install Android dependencies
        run: |
          flutter doctor --android-licenses
          flutter pub get

      # Step 5: Build the Android APK
      - name: Build Android APK
        run: flutter build apk --release

      # Step 6: Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@abc1234567890abcdef1234567890abcdef1234
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
